# Generated by Django 4.2.1 on 2023-05-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nombre_de_la_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipodocumento',
            old_name='Descripción',
            new_name='descripción',
        ),
        migrations.RemoveField(
            model_name='tipodocumento',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(default='Default Value', max_length=50),
        ),
    ]
